---
all:
  vars:
    ansible_user: devops
    ansible_port: 10022
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_become: true
    ansible_become_method: sudo
  children:
    prometheus:
      hosts:
        etcd02:
          ansible_host: 172.16.5.172
          replica_name: prom1
        etcd03:
          ansible_host: 172.16.5.173
          replica_name: prom2
    thanos_sidecar:
      hosts:
        etcd02:
          ansible_host: 172.16.5.172
        etcd03:
          ansible_host: 172.16.5.173
    thanos_query:
      hosts:
        etcd02:
          ansible_host: 172.16.5.172
    thanos_store:
      hosts:
        etcd03:
          ansible_host: 172.16.5.173
    thanos_compactor:
      hosts:
        etcd03:
          ansible_host: 172.16.5.173
    grafana:
      hosts:
        etcd02:
          ansible_host: 172.16.5.172
    tempo:
      hosts:
        etcd03:
          ansible_host: 172.16.5.173