all:

  vars:
    ansible_user: root          
    ansible_port: 10022         
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_method: sudo

  children:
    prometheus:
      hosts:
        server1:
          ansible_host: 172.16.15.181
          replica_name: prom1
        server2:
          ansible_host: 172.16.15.188
          replica_name: prom2
    grafana:
      hosts:
        server3:
          ansible_host: 172.16.15.194
    thanos_query:
      hosts:
        server3: {}


